#!/usr/bin/env python
# License: GPLv3 Copyright: 2021, Kovid Goyal <kovid at kovidgoyal.net>

# After editing this file run ./gen-config.py to apply the changes

import string

from alatty.conf.types import Action, Definition
from alatty.constants import website_url

definition = Definition(
    'alatty',
    Action('map', 'parse_map', {'keyboard_modes': 'KeyboardModeMap', 'alias_map': 'AliasMap'},
           ['KeyDefinition', 'alatty.fast_data_types.SingleKey']),
    Action('mouse_map', 'parse_mouse_map', {'mousemap': 'MouseMap'}, ['MouseMapping']),
    has_color_table=True,
)
definition.add_deprecation('deprecated_hide_window_decorations_aliases', 'x11_hide_window_decorations', 'macos_hide_titlebar')
definition.add_deprecation('deprecated_macos_show_window_title_in_menubar_alias', 'macos_show_window_title_in_menubar')
definition.add_deprecation('deprecated_send_text', 'send_text')
definition.add_deprecation('deprecated_adjust_line_height', 'adjust_line_height', 'adjust_column_width', 'adjust_baseline')

agr = definition.add_group
egr = definition.end_group
opt = definition.add_option
map = definition.add_map
mma = definition.add_mouse_map

# fonts {{{
agr('fonts', 'Fonts', '''
alatty has very powerful font management. You can configure individual font faces
and even specify special fonts for particular characters.
''')

opt('font_family', 'monospace')
opt('bold_font', 'auto')
opt('italic_font', 'auto')
opt('bold_italic_font', 'auto')
opt('font_size', '11.0', option_type='to_font_size', ctype='double')
opt('force_ltr', 'no', option_type='to_bool', ctype='bool')
opt('+symbol_map', 'U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols', option_type='symbol_map', add_to_default=False)
opt('+narrow_symbols', 'U+E0A0-U+E0A3,U+E0C0-U+E0C7 1', option_type='narrow_symbols', add_to_default=False)
opt('disable_ligatures', 'never', option_type='disable_ligatures', ctype='int')
opt('+font_features', 'none', option_type='font_features', add_to_default=False)
opt('+modify_font', '', option_type='modify_font', ctype='!modify_font', add_to_default=False)

opt('undercurl_style', 'thin-sparse', choices=('thin-sparse', 'thin-dense', 'thick-sparse', 'thick-dense'))
opt('text_composition_strategy', 'platform', ctype='!text_composition_strategy')

opt('cursor_text_color', '#111111', option_type='cursor_text_color')
opt('cursor_shape', 'block', option_type='to_cursor_shape', ctype='int')
opt('cursor_beam_thickness', '1.5', option_type='positive_float', ctype='float')
opt('cursor_underline_thickness', '2.0', option_type='positive_float', ctype='float')

opt('cursor_blink_interval', '-1', option_type='float', ctype='time')

opt('cursor_stop_blinking_after', '15.0', option_type='positive_float', ctype='time')
egr()  # }}}


# scrollback {{{
agr('scrollback', 'Scrollback')
opt('scrollback_lines', '2000', option_type='scrollback_lines')
opt('scrollback_pager', 'less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER', option_type='to_cmdline')
opt('scrollback_pager_history_size', '0', option_type='scrollback_pager_history_size', ctype='uint')
opt('scrollback_fill_enlarged_window', 'no', option_type='to_bool', ctype='bool')
opt('wheel_scroll_multiplier', '5.0', option_type='float', ctype='double')
opt('wheel_scroll_min_lines', '1', option_type='int', ctype='int')
opt('touch_scroll_multiplier', '1.0', option_type='float', ctype='double')
egr()  # }}}


# mouse {{{
agr('mouse', 'Mouse')

opt('mouse_hide_wait', '3.0', macos_default='0.0', option_type='float', ctype='time')

opt('url_color', '#0087bd', option_type='to_color', ctype='color_as_int')
opt('url_style', 'curly', option_type='url_style', ctype='uint')
opt('open_url_with', 'default', option_type='to_cmdline')
opt('url_prefixes', 'file ftp ftps gemini git gopher http https irc ircs alatty mailto news sftp ssh', option_type='url_prefixes', ctype='!url_prefixes')
opt('detect_urls', 'yes', option_type='to_bool', ctype='bool')

opt('url_excluded_characters', '', option_type='python_string', ctype='!url_excluded_characters')
opt('show_hyperlink_targets', 'no', option_type='to_bool', ctype='bool')
opt('paste_actions', 'quote-urls-at-prompt,confirm', option_type='paste_actions')

opt('strip_trailing_spaces', 'never', choices=('always', 'never', 'smart'))

opt('select_by_word_characters', '@-./_~?&=%+#', ctype='!select_by_word_characters')

opt('select_by_word_characters_forward', '', ctype='!select_by_word_characters_forward')

opt('click_interval', '-1.0', option_type='float', ctype='time')

opt('focus_follows_mouse', 'no', option_type='to_bool', ctype='bool')

pointer_shape_names = (
# start pointer shape names (auto generated by gen-key-constants.py do not edit)
    'arrow',
    'beam',
    'text',
    'pointer',
    'hand',
    'help',
    'wait',
    'progress',
    'crosshair',
    'cell',
    'vertical-text',
    'move',
    'e-resize',
    'ne-resize',
    'nw-resize',
    'n-resize',
    'se-resize',
    'sw-resize',
    's-resize',
    'w-resize',
    'ew-resize',
    'ns-resize',
    'nesw-resize',
    'nwse-resize',
    'zoom-in',
    'zoom-out',
    'alias',
    'copy',
    'not-allowed',
    'no-drop',
    'grab',
    'grabbing',
# end pointer shape names
)

opt('pointer_shape_when_grabbed', 'arrow', choices=pointer_shape_names, ctype='pointer_shape')
opt('default_pointer_shape', 'beam', choices=pointer_shape_names, ctype='pointer_shape')
opt('pointer_shape_when_dragging', 'beam', choices=pointer_shape_names, ctype='pointer_shape')


# mouse.mousemap {{{
agr('mouse.mousemap', 'Mouse actions', '')
opt('clear_all_mouse_actions', 'no', option_type='clear_all_mouse_actions')
mma('Click the link under the mouse or move the cursor', 'click_url_or_select left click ungrabbed mouse_handle_click selection link prompt')
mma('Click the link under the mouse or move the cursor even when grabbed', 'click_url_or_select_grabbed shift+left click grabbed,ungrabbed mouse_handle_click selection link prompt')
mma('Click the link under the mouse cursor', 'click_url ctrl+shift+left release grabbed,ungrabbed mouse_handle_click link')
mma('Discard press event for link click', 'click_url_discard ctrl+shift+left press grabbed discard_event')
mma('Paste from the primary selection', 'paste_selection middle release ungrabbed paste_from_selection')
mma('Start selecting text', 'start_simple_selection left press ungrabbed mouse_selection normal')
mma('Start selecting text in a rectangle', 'start_rectangle_selection ctrl+alt+left press ungrabbed mouse_selection rectangle')
mma('Select a word', 'select_word left doublepress ungrabbed mouse_selection word')
mma('Select a line', 'select_line left triplepress ungrabbed mouse_selection line')
mma('Select line from point', 'select_line_from_point ctrl+alt+left triplepress ungrabbed mouse_selection line_from_point')
mma('Extend the current selection', 'extend_selection right press ungrabbed mouse_selection extend')
mma('Paste from the primary selection even when grabbed', 'paste_selection_grabbed shift+middle release ungrabbed,grabbed paste_selection')
mma('Discard press event for middle click paste', 'paste_selection_grabbed shift+middle press grabbed discard_event')
mma('Start selecting text even when grabbed', 'start_simple_selection_grabbed shift+left press ungrabbed,grabbed mouse_selection normal')
mma('Start selecting text in a rectangle even when grabbed', 'start_rectangle_selection_grabbed ctrl+shift+alt+left press ungrabbed,grabbed mouse_selection rectangle')
mma('Select a word even when grabbed', 'select_word_grabbed shift+left doublepress ungrabbed,grabbed mouse_selection word')
mma('Select a line even when grabbed', 'select_line_grabbed shift+left triplepress ungrabbed,grabbed mouse_selection line')
mma('Select line from point even when grabbed', 'select_line_from_point_grabbed ctrl+shift+alt+left triplepress ungrabbed,grabbed mouse_selection line_from_point')
mma('Extend the current selection even when grabbed', 'extend_selection_grabbed shift+right press ungrabbed,grabbed mouse_selection extend')
mma('Show clicked command output in pager', 'show_clicked_cmd_output_ungrabbed ctrl+shift+right press ungrabbed mouse_show_command_output')
egr()  # }}}
egr()  # }}}


# performance {{{
agr('performance', 'Performance tuning')
opt('repaint_delay', '10', option_type='positive_int', ctype='time-ms')
opt('input_delay', '3', option_type='positive_int', ctype='time-ms')
opt('sync_to_monitor', 'yes', option_type='to_bool', ctype='bool')
egr()  # }}}


# bell {{{
agr('bell', 'Terminal bell')
opt('enable_audio_bell', 'yes', option_type='to_bool', ctype='bool')
opt('visual_bell_duration', '0.0', option_type='positive_float', ctype='time')
opt('visual_bell_color', 'none', option_type='to_color_or_none')
opt('window_alert_on_bell', 'yes', option_type='to_bool', ctype='bool')
opt('bell_on_tab', '"🔔 "', option_type='bell_on_tab')
opt('command_on_bell', 'none', option_type='to_cmdline')
opt('bell_path', 'none', option_type='config_or_absolute_path', ctype='!bell_path')
opt('linux_bell_theme', '__custom', ctype='!bell_theme')
egr()  # }}}


# window {{{
agr('window', 'Window layout')
opt('remember_window_size', 'yes', option_type='to_bool')
opt('initial_window_width', '640', option_type='window_size')
opt('initial_window_height', '400', option_type='window_size')
opt('enabled_layouts', '*', option_type='to_layout_names')
opt('window_resize_step_cells', '2', option_type='positive_int')
opt('window_resize_step_lines', '2', option_type='positive_int')
opt('window_border_width', '0.5pt', option_type='window_border_width')
opt('draw_minimal_borders', 'yes', option_type='to_bool')
opt('window_margin_width', '0', option_type='edge_width')
opt('single_window_margin_width', '-1', option_type='optional_edge_width')
opt('window_padding_width', '0', option_type='edge_width')
opt('single_window_padding_width', '-1', option_type='optional_edge_width')
opt('placement_strategy', 'center', choices=('center', 'top-left'))
opt('active_border_color', '#00ff00', option_type='to_color_or_none', ctype='active_border_color')
opt('inactive_border_color', '#cccccc', option_type='to_color', ctype='color_as_int')
opt('bell_border_color', '#ff5a00', option_type='to_color', ctype='color_as_int')
opt('inactive_text_alpha', '1.0', option_type='unit_float', ctype='float')
opt('hide_window_decorations', 'no', option_type='hide_window_decorations', ctype='uint')
opt('window_logo_path', 'none', option_type='config_or_absolute_path', ctype='!window_logo_path')
opt('window_logo_position', 'bottom-right',
    choices=('top-left', 'top', 'top-right', 'left', 'center', 'right', 'bottom-left', 'bottom', 'bottom-right'),
    ctype='bganchor')
opt('window_logo_alpha', '0.5', option_type='unit_float', ctype='float')
opt('resize_debounce_time', '0.1 0.5', option_type='resize_debounce_time', ctype='!resize_debounce_time')
opt('resize_in_steps', 'no', option_type='to_bool', ctype='bool')
opt('visual_window_select_characters', defval=string.digits[1:] + '0' + string.ascii_uppercase, option_type='visual_window_select_characters')
opt('confirm_os_window_close', '-1', option_type='int')
egr()  # }}}


# tabbar {{{
agr('tabbar', 'Tab bar')

opt('tab_bar_edge', 'bottom', option_type='tab_bar_edge', ctype='int')

opt('tab_bar_margin_width', '0.0', option_type='positive_float')

opt('tab_bar_margin_height', '0.0 0.0',
    option_type='tab_bar_margin_height', ctype='!tab_bar_margin_height',
    )

opt('tab_bar_style', 'fade',
    choices=('fade', 'hidden', 'powerline', 'separator', 'slant', 'custom'),
    ctype='!tab_bar_style',
    )

opt('tab_bar_align', 'left',
    choices=('left', 'center', 'right'),
    )

opt('tab_bar_min_tabs', '2', option_type='tab_bar_min_tabs', ctype='uint')

opt('tab_switch_strategy', 'previous',
    choices=('last', 'left', 'previous', 'right'),
    )

opt('tab_fade', '0.25 0.5 0.75 1',
    option_type='tab_fade',
    )

opt('tab_separator', '" ┇"',
    option_type='tab_separator',
    )

opt('tab_powerline_style', 'angled',
    choices=('angled', 'round', 'slanted'),
    )

opt('tab_activity_symbol', 'none',
    option_type='tab_activity_symbol',
    )

opt('tab_title_max_length', '0',
    option_type='positive_int',
    )

opt('tab_title_template', '"{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"',
    option_type='tab_title_template',
    )

opt('active_tab_title_template', 'none',
    option_type='active_tab_title_template',
    )

opt('active_tab_foreground', '#000', option_type='to_color')

opt('active_tab_background', '#eee',
    option_type='to_color',
    )

opt('active_tab_font_style', 'bold-italic',
    option_type='tab_font_style',
    )

opt('inactive_tab_foreground', '#444',
    option_type='to_color',
    )

opt('inactive_tab_background', '#999',
    option_type='to_color',
    )

opt('inactive_tab_font_style', 'normal',
    option_type='tab_font_style',
    )

opt('tab_bar_background', 'none',
    option_type='to_color_or_none', ctype='color_or_none_as_int',
    )

opt('tab_bar_margin_color', 'none',
    option_type='to_color_or_none', ctype='color_or_none_as_int',
    )
egr()  # }}}


# colors {{{
agr('colors', 'Color scheme')

opt('foreground', '#dddddd', option_type='to_color', ctype='color_as_int')

opt('background', '#000000',
    option_type='to_color', ctype='color_as_int',
    )

opt('background_opacity', '1.0',
    option_type='unit_float', ctype='float',
    )

opt('background_blur', '0', option_type='int', ctype='int')

opt('background_image_linear', 'no', option_type='to_bool', ctype='bool')

opt('dynamic_background_opacity', 'no',
    option_type='to_bool', ctype='bool',
    )

opt('background_tint', '0.0',
    option_type='unit_float', ctype='float',
    )

opt('background_tint_gaps', '1.0',
    option_type='unit_float', ctype='float',
    )

opt('dim_opacity', '0.4',
    option_type='unit_float', ctype='float',
    )

opt('selection_foreground', '#000000',
    option_type='to_color_or_none',
    )

opt('selection_background', '#fffacd',
    option_type='to_color_or_none',
    )


# colors.table {{{
agr('colors.table', 'The color table', '''
The 256 terminal colors. There are 8 basic colors, each color has a dull and
bright version, for the first 16 colors. You can set the remaining 240 colors as
color16 to color255.
''')

opt('color0', '#000000', option_type='to_color')

opt('color8', '#767676', option_type='to_color')

opt('color1', '#cc0403', option_type='to_color')

opt('color9', '#f2201f', option_type='to_color')

opt('color2', '#19cb00', option_type='to_color')

opt('color10', '#23fd00', option_type='to_color')

opt('color3', '#cecb00', option_type='to_color')

opt('color11', '#fffd00', option_type='to_color')

opt('color4', '#0d73cc', option_type='to_color')

opt('color12', '#1a8fff', option_type='to_color')

opt('color5', '#cb1ed1', option_type='to_color')

opt('color13', '#fd28ff', option_type='to_color')

opt('color6', '#0dcdcd', option_type='to_color')

opt('color14', '#14ffff', option_type='to_color')

opt('color7', '#dddddd', option_type='to_color')

opt('color15', '#ffffff', option_type='to_color')

opt('mark1_foreground', 'black',
    option_type='to_color', ctype='color_as_int',
    )

opt('mark1_background', '#98d3cb',
    option_type='to_color', ctype='color_as_int',
    )

opt('mark2_foreground', 'black',
    option_type='to_color', ctype='color_as_int',
    )

opt('mark2_background', '#f2dcd3',
    option_type='to_color', ctype='color_as_int',
    )

opt('mark3_foreground', 'black',
    option_type='to_color', ctype='color_as_int',
    )

opt('mark3_background', '#f274bc',
    option_type='to_color', ctype='color_as_int',
    )

opt('color16', '#000000',
    option_type='to_color',
    documented=False,
    )

opt('color17', '#00005f',
    option_type='to_color',
    documented=False,
    )

opt('color18', '#000087',
    option_type='to_color',
    documented=False,
    )

opt('color19', '#0000af',
    option_type='to_color',
    documented=False,
    )

opt('color20', '#0000d7',
    option_type='to_color',
    documented=False,
    )

opt('color21', '#0000ff',
    option_type='to_color',
    documented=False,
    )

opt('color22', '#005f00',
    option_type='to_color',
    documented=False,
    )

opt('color23', '#005f5f',
    option_type='to_color',
    documented=False,
    )

opt('color24', '#005f87',
    option_type='to_color',
    documented=False,
    )

opt('color25', '#005faf',
    option_type='to_color',
    documented=False,
    )

opt('color26', '#005fd7',
    option_type='to_color',
    documented=False,
    )

opt('color27', '#005fff',
    option_type='to_color',
    documented=False,
    )

opt('color28', '#008700',
    option_type='to_color',
    documented=False,
    )

opt('color29', '#00875f',
    option_type='to_color',
    documented=False,
    )

opt('color30', '#008787',
    option_type='to_color',
    documented=False,
    )

opt('color31', '#0087af',
    option_type='to_color',
    documented=False,
    )

opt('color32', '#0087d7',
    option_type='to_color',
    documented=False,
    )

opt('color33', '#0087ff',
    option_type='to_color',
    documented=False,
    )

opt('color34', '#00af00',
    option_type='to_color',
    documented=False,
    )

opt('color35', '#00af5f',
    option_type='to_color',
    documented=False,
    )

opt('color36', '#00af87',
    option_type='to_color',
    documented=False,
    )

opt('color37', '#00afaf',
    option_type='to_color',
    documented=False,
    )

opt('color38', '#00afd7',
    option_type='to_color',
    documented=False,
    )

opt('color39', '#00afff',
    option_type='to_color',
    documented=False,
    )

opt('color40', '#00d700',
    option_type='to_color',
    documented=False,
    )

opt('color41', '#00d75f',
    option_type='to_color',
    documented=False,
    )

opt('color42', '#00d787',
    option_type='to_color',
    documented=False,
    )

opt('color43', '#00d7af',
    option_type='to_color',
    documented=False,
    )

opt('color44', '#00d7d7',
    option_type='to_color',
    documented=False,
    )

opt('color45', '#00d7ff',
    option_type='to_color',
    documented=False,
    )

opt('color46', '#00ff00',
    option_type='to_color',
    documented=False,
    )

opt('color47', '#00ff5f',
    option_type='to_color',
    documented=False,
    )

opt('color48', '#00ff87',
    option_type='to_color',
    documented=False,
    )

opt('color49', '#00ffaf',
    option_type='to_color',
    documented=False,
    )

opt('color50', '#00ffd7',
    option_type='to_color',
    documented=False,
    )

opt('color51', '#00ffff',
    option_type='to_color',
    documented=False,
    )

opt('color52', '#5f0000',
    option_type='to_color',
    documented=False,
    )

opt('color53', '#5f005f',
    option_type='to_color',
    documented=False,
    )

opt('color54', '#5f0087',
    option_type='to_color',
    documented=False,
    )

opt('color55', '#5f00af',
    option_type='to_color',
    documented=False,
    )

opt('color56', '#5f00d7',
    option_type='to_color',
    documented=False,
    )

opt('color57', '#5f00ff',
    option_type='to_color',
    documented=False,
    )

opt('color58', '#5f5f00',
    option_type='to_color',
    documented=False,
    )

opt('color59', '#5f5f5f',
    option_type='to_color',
    documented=False,
    )

opt('color60', '#5f5f87',
    option_type='to_color',
    documented=False,
    )

opt('color61', '#5f5faf',
    option_type='to_color',
    documented=False,
    )

opt('color62', '#5f5fd7',
    option_type='to_color',
    documented=False,
    )

opt('color63', '#5f5fff',
    option_type='to_color',
    documented=False,
    )

opt('color64', '#5f8700',
    option_type='to_color',
    documented=False,
    )

opt('color65', '#5f875f',
    option_type='to_color',
    documented=False,
    )

opt('color66', '#5f8787',
    option_type='to_color',
    documented=False,
    )

opt('color67', '#5f87af',
    option_type='to_color',
    documented=False,
    )

opt('color68', '#5f87d7',
    option_type='to_color',
    documented=False,
    )

opt('color69', '#5f87ff',
    option_type='to_color',
    documented=False,
    )

opt('color70', '#5faf00',
    option_type='to_color',
    documented=False,
    )

opt('color71', '#5faf5f',
    option_type='to_color',
    documented=False,
    )

opt('color72', '#5faf87',
    option_type='to_color',
    documented=False,
    )

opt('color73', '#5fafaf',
    option_type='to_color',
    documented=False,
    )

opt('color74', '#5fafd7',
    option_type='to_color',
    documented=False,
    )

opt('color75', '#5fafff',
    option_type='to_color',
    documented=False,
    )

opt('color76', '#5fd700',
    option_type='to_color',
    documented=False,
    )

opt('color77', '#5fd75f',
    option_type='to_color',
    documented=False,
    )

opt('color78', '#5fd787',
    option_type='to_color',
    documented=False,
    )

opt('color79', '#5fd7af',
    option_type='to_color',
    documented=False,
    )

opt('color80', '#5fd7d7',
    option_type='to_color',
    documented=False,
    )

opt('color81', '#5fd7ff',
    option_type='to_color',
    documented=False,
    )

opt('color82', '#5fff00',
    option_type='to_color',
    documented=False,
    )

opt('color83', '#5fff5f',
    option_type='to_color',
    documented=False,
    )

opt('color84', '#5fff87',
    option_type='to_color',
    documented=False,
    )

opt('color85', '#5fffaf',
    option_type='to_color',
    documented=False,
    )

opt('color86', '#5fffd7',
    option_type='to_color',
    documented=False,
    )

opt('color87', '#5fffff',
    option_type='to_color',
    documented=False,
    )

opt('color88', '#870000',
    option_type='to_color',
    documented=False,
    )

opt('color89', '#87005f',
    option_type='to_color',
    documented=False,
    )

opt('color90', '#870087',
    option_type='to_color',
    documented=False,
    )

opt('color91', '#8700af',
    option_type='to_color',
    documented=False,
    )

opt('color92', '#8700d7',
    option_type='to_color',
    documented=False,
    )

opt('color93', '#8700ff',
    option_type='to_color',
    documented=False,
    )

opt('color94', '#875f00',
    option_type='to_color',
    documented=False,
    )

opt('color95', '#875f5f',
    option_type='to_color',
    documented=False,
    )

opt('color96', '#875f87',
    option_type='to_color',
    documented=False,
    )

opt('color97', '#875faf',
    option_type='to_color',
    documented=False,
    )

opt('color98', '#875fd7',
    option_type='to_color',
    documented=False,
    )

opt('color99', '#875fff',
    option_type='to_color',
    documented=False,
    )

opt('color100', '#878700',
    option_type='to_color',
    documented=False,
    )

opt('color101', '#87875f',
    option_type='to_color',
    documented=False,
    )

opt('color102', '#878787',
    option_type='to_color',
    documented=False,
    )

opt('color103', '#8787af',
    option_type='to_color',
    documented=False,
    )

opt('color104', '#8787d7',
    option_type='to_color',
    documented=False,
    )

opt('color105', '#8787ff',
    option_type='to_color',
    documented=False,
    )

opt('color106', '#87af00',
    option_type='to_color',
    documented=False,
    )

opt('color107', '#87af5f',
    option_type='to_color',
    documented=False,
    )

opt('color108', '#87af87',
    option_type='to_color',
    documented=False,
    )

opt('color109', '#87afaf',
    option_type='to_color',
    documented=False,
    )

opt('color110', '#87afd7',
    option_type='to_color',
    documented=False,
    )

opt('color111', '#87afff',
    option_type='to_color',
    documented=False,
    )

opt('color112', '#87d700',
    option_type='to_color',
    documented=False,
    )

opt('color113', '#87d75f',
    option_type='to_color',
    documented=False,
    )

opt('color114', '#87d787',
    option_type='to_color',
    documented=False,
    )

opt('color115', '#87d7af',
    option_type='to_color',
    documented=False,
    )

opt('color116', '#87d7d7',
    option_type='to_color',
    documented=False,
    )

opt('color117', '#87d7ff',
    option_type='to_color',
    documented=False,
    )

opt('color118', '#87ff00',
    option_type='to_color',
    documented=False,
    )

opt('color119', '#87ff5f',
    option_type='to_color',
    documented=False,
    )

opt('color120', '#87ff87',
    option_type='to_color',
    documented=False,
    )

opt('color121', '#87ffaf',
    option_type='to_color',
    documented=False,
    )

opt('color122', '#87ffd7',
    option_type='to_color',
    documented=False,
    )

opt('color123', '#87ffff',
    option_type='to_color',
    documented=False,
    )

opt('color124', '#af0000',
    option_type='to_color',
    documented=False,
    )

opt('color125', '#af005f',
    option_type='to_color',
    documented=False,
    )

opt('color126', '#af0087',
    option_type='to_color',
    documented=False,
    )

opt('color127', '#af00af',
    option_type='to_color',
    documented=False,
    )

opt('color128', '#af00d7',
    option_type='to_color',
    documented=False,
    )

opt('color129', '#af00ff',
    option_type='to_color',
    documented=False,
    )

opt('color130', '#af5f00',
    option_type='to_color',
    documented=False,
    )

opt('color131', '#af5f5f',
    option_type='to_color',
    documented=False,
    )

opt('color132', '#af5f87',
    option_type='to_color',
    documented=False,
    )

opt('color133', '#af5faf',
    option_type='to_color',
    documented=False,
    )

opt('color134', '#af5fd7',
    option_type='to_color',
    documented=False,
    )

opt('color135', '#af5fff',
    option_type='to_color',
    documented=False,
    )

opt('color136', '#af8700',
    option_type='to_color',
    documented=False,
    )

opt('color137', '#af875f',
    option_type='to_color',
    documented=False,
    )

opt('color138', '#af8787',
    option_type='to_color',
    documented=False,
    )

opt('color139', '#af87af',
    option_type='to_color',
    documented=False,
    )

opt('color140', '#af87d7',
    option_type='to_color',
    documented=False,
    )

opt('color141', '#af87ff',
    option_type='to_color',
    documented=False,
    )

opt('color142', '#afaf00',
    option_type='to_color',
    documented=False,
    )

opt('color143', '#afaf5f',
    option_type='to_color',
    documented=False,
    )

opt('color144', '#afaf87',
    option_type='to_color',
    documented=False,
    )

opt('color145', '#afafaf',
    option_type='to_color',
    documented=False,
    )

opt('color146', '#afafd7',
    option_type='to_color',
    documented=False,
    )

opt('color147', '#afafff',
    option_type='to_color',
    documented=False,
    )

opt('color148', '#afd700',
    option_type='to_color',
    documented=False,
    )

opt('color149', '#afd75f',
    option_type='to_color',
    documented=False,
    )

opt('color150', '#afd787',
    option_type='to_color',
    documented=False,
    )

opt('color151', '#afd7af',
    option_type='to_color',
    documented=False,
    )

opt('color152', '#afd7d7',
    option_type='to_color',
    documented=False,
    )

opt('color153', '#afd7ff',
    option_type='to_color',
    documented=False,
    )

opt('color154', '#afff00',
    option_type='to_color',
    documented=False,
    )

opt('color155', '#afff5f',
    option_type='to_color',
    documented=False,
    )

opt('color156', '#afff87',
    option_type='to_color',
    documented=False,
    )

opt('color157', '#afffaf',
    option_type='to_color',
    documented=False,
    )

opt('color158', '#afffd7',
    option_type='to_color',
    documented=False,
    )

opt('color159', '#afffff',
    option_type='to_color',
    documented=False,
    )

opt('color160', '#d70000',
    option_type='to_color',
    documented=False,
    )

opt('color161', '#d7005f',
    option_type='to_color',
    documented=False,
    )

opt('color162', '#d70087',
    option_type='to_color',
    documented=False,
    )

opt('color163', '#d700af',
    option_type='to_color',
    documented=False,
    )

opt('color164', '#d700d7',
    option_type='to_color',
    documented=False,
    )

opt('color165', '#d700ff',
    option_type='to_color',
    documented=False,
    )

opt('color166', '#d75f00',
    option_type='to_color',
    documented=False,
    )

opt('color167', '#d75f5f',
    option_type='to_color',
    documented=False,
    )

opt('color168', '#d75f87',
    option_type='to_color',
    documented=False,
    )

opt('color169', '#d75faf',
    option_type='to_color',
    documented=False,
    )

opt('color170', '#d75fd7',
    option_type='to_color',
    documented=False,
    )

opt('color171', '#d75fff',
    option_type='to_color',
    documented=False,
    )

opt('color172', '#d78700',
    option_type='to_color',
    documented=False,
    )

opt('color173', '#d7875f',
    option_type='to_color',
    documented=False,
    )

opt('color174', '#d78787',
    option_type='to_color',
    documented=False,
    )

opt('color175', '#d787af',
    option_type='to_color',
    documented=False,
    )

opt('color176', '#d787d7',
    option_type='to_color',
    documented=False,
    )

opt('color177', '#d787ff',
    option_type='to_color',
    documented=False,
    )

opt('color178', '#d7af00',
    option_type='to_color',
    documented=False,
    )

opt('color179', '#d7af5f',
    option_type='to_color',
    documented=False,
    )

opt('color180', '#d7af87',
    option_type='to_color',
    documented=False,
    )

opt('color181', '#d7afaf',
    option_type='to_color',
    documented=False,
    )

opt('color182', '#d7afd7',
    option_type='to_color',
    documented=False,
    )

opt('color183', '#d7afff',
    option_type='to_color',
    documented=False,
    )

opt('color184', '#d7d700',
    option_type='to_color',
    documented=False,
    )

opt('color185', '#d7d75f',
    option_type='to_color',
    documented=False,
    )

opt('color186', '#d7d787',
    option_type='to_color',
    documented=False,
    )

opt('color187', '#d7d7af',
    option_type='to_color',
    documented=False,
    )

opt('color188', '#d7d7d7',
    option_type='to_color',
    documented=False,
    )

opt('color189', '#d7d7ff',
    option_type='to_color',
    documented=False,
    )

opt('color190', '#d7ff00',
    option_type='to_color',
    documented=False,
    )

opt('color191', '#d7ff5f',
    option_type='to_color',
    documented=False,
    )

opt('color192', '#d7ff87',
    option_type='to_color',
    documented=False,
    )

opt('color193', '#d7ffaf',
    option_type='to_color',
    documented=False,
    )

opt('color194', '#d7ffd7',
    option_type='to_color',
    documented=False,
    )

opt('color195', '#d7ffff',
    option_type='to_color',
    documented=False,
    )

opt('color196', '#ff0000',
    option_type='to_color',
    documented=False,
    )

opt('color197', '#ff005f',
    option_type='to_color',
    documented=False,
    )

opt('color198', '#ff0087',
    option_type='to_color',
    documented=False,
    )

opt('color199', '#ff00af',
    option_type='to_color',
    documented=False,
    )

opt('color200', '#ff00d7',
    option_type='to_color',
    documented=False,
    )

opt('color201', '#ff00ff',
    option_type='to_color',
    documented=False,
    )

opt('color202', '#ff5f00',
    option_type='to_color',
    documented=False,
    )

opt('color203', '#ff5f5f',
    option_type='to_color',
    documented=False,
    )

opt('color204', '#ff5f87',
    option_type='to_color',
    documented=False,
    )

opt('color205', '#ff5faf',
    option_type='to_color',
    documented=False,
    )

opt('color206', '#ff5fd7',
    option_type='to_color',
    documented=False,
    )

opt('color207', '#ff5fff',
    option_type='to_color',
    documented=False,
    )

opt('color208', '#ff8700',
    option_type='to_color',
    documented=False,
    )

opt('color209', '#ff875f',
    option_type='to_color',
    documented=False,
    )

opt('color210', '#ff8787',
    option_type='to_color',
    documented=False,
    )

opt('color211', '#ff87af',
    option_type='to_color',
    documented=False,
    )

opt('color212', '#ff87d7',
    option_type='to_color',
    documented=False,
    )

opt('color213', '#ff87ff',
    option_type='to_color',
    documented=False,
    )

opt('color214', '#ffaf00',
    option_type='to_color',
    documented=False,
    )

opt('color215', '#ffaf5f',
    option_type='to_color',
    documented=False,
    )

opt('color216', '#ffaf87',
    option_type='to_color',
    documented=False,
    )

opt('color217', '#ffafaf',
    option_type='to_color',
    documented=False,
    )

opt('color218', '#ffafd7',
    option_type='to_color',
    documented=False,
    )

opt('color219', '#ffafff',
    option_type='to_color',
    documented=False,
    )

opt('color220', '#ffd700',
    option_type='to_color',
    documented=False,
    )

opt('color221', '#ffd75f',
    option_type='to_color',
    documented=False,
    )

opt('color222', '#ffd787',
    option_type='to_color',
    documented=False,
    )

opt('color223', '#ffd7af',
    option_type='to_color',
    documented=False,
    )

opt('color224', '#ffd7d7',
    option_type='to_color',
    documented=False,
    )

opt('color225', '#ffd7ff',
    option_type='to_color',
    documented=False,
    )

opt('color226', '#ffff00',
    option_type='to_color',
    documented=False,
    )

opt('color227', '#ffff5f',
    option_type='to_color',
    documented=False,
    )

opt('color228', '#ffff87',
    option_type='to_color',
    documented=False,
    )

opt('color229', '#ffffaf',
    option_type='to_color',
    documented=False,
    )

opt('color230', '#ffffd7',
    option_type='to_color',
    documented=False,
    )

opt('color231', '#ffffff',
    option_type='to_color',
    documented=False,
    )

opt('color232', '#080808',
    option_type='to_color',
    documented=False,
    )

opt('color233', '#121212',
    option_type='to_color',
    documented=False,
    )

opt('color234', '#1c1c1c',
    option_type='to_color',
    documented=False,
    )

opt('color235', '#262626',
    option_type='to_color',
    documented=False,
    )

opt('color236', '#303030',
    option_type='to_color',
    documented=False,
    )

opt('color237', '#3a3a3a',
    option_type='to_color',
    documented=False,
    )

opt('color238', '#444444',
    option_type='to_color',
    documented=False,
    )

opt('color239', '#4e4e4e',
    option_type='to_color',
    documented=False,
    )

opt('color240', '#585858',
    option_type='to_color',
    documented=False,
    )

opt('color241', '#626262',
    option_type='to_color',
    documented=False,
    )

opt('color242', '#6c6c6c',
    option_type='to_color',
    documented=False,
    )

opt('color243', '#767676',
    option_type='to_color',
    documented=False,
    )

opt('color244', '#808080',
    option_type='to_color',
    documented=False,
    )

opt('color245', '#8a8a8a',
    option_type='to_color',
    documented=False,
    )

opt('color246', '#949494',
    option_type='to_color',
    documented=False,
    )

opt('color247', '#9e9e9e',
    option_type='to_color',
    documented=False,
    )

opt('color248', '#a8a8a8',
    option_type='to_color',
    documented=False,
    )

opt('color249', '#b2b2b2',
    option_type='to_color',
    documented=False,
    )

opt('color250', '#bcbcbc',
    option_type='to_color',
    documented=False,
    )

opt('color251', '#c6c6c6',
    option_type='to_color',
    documented=False,
    )

opt('color252', '#d0d0d0',
    option_type='to_color',
    documented=False,
    )

opt('color253', '#dadada',
    option_type='to_color',
    documented=False,
    )

opt('color254', '#e4e4e4',
    option_type='to_color',
    documented=False,
    )

opt('color255', '#eeeeee',
    option_type='to_color',
    documented=False,
    )
egr()  # }}}
egr()  # }}}


# advanced {{{
agr('advanced', 'Advanced')

opt('shell', '.',
    )

opt('editor', '.',
    )

opt('close_on_child_death', 'no',
    option_type='to_bool', ctype='bool',
    )

opt('+remote_control_password', '',
    option_type='remote_control_password',
    add_to_default=False,
    )

opt('listen_on', 'none',
    )

opt('+env', '',
    option_type='env',
    add_to_default=False,
    )

opt('+watcher', '',
    option_type='store_multiple',
    add_to_default=False,
    )

opt('+exe_search_path', '',
    option_type='store_multiple',
    add_to_default=False,
    )

opt('update_check_interval', '24',
    option_type='float',
    )

opt('startup_session', 'none',
    option_type='config_or_absolute_path',
    )

opt('clipboard_control', 'write-clipboard write-primary read-clipboard-ask read-primary-ask',
    option_type='clipboard_control',
    )

opt('clipboard_max_size', '512',
    option_type='positive_float',
    )

opt('allow_hyperlinks', 'yes',
    option_type='allow_hyperlinks', ctype='bool',
    )

opt('shell_integration', 'enabled',
    option_type='shell_integration',
    )

opt('allow_cloning', 'ask',
    choices=('yes', 'y', 'true', 'no', 'n', 'false', 'ask'),
    )

opt('clone_source_strategies', 'venv,conda,env_var,path',
    option_type='clone_source_strategies',
    )

opt('notify_on_cmd_finish', 'never', option_type='notify_on_cmd_finish')

opt('term', 'xterm-alatty',
    )

opt('forward_stdio', 'no', option_type='to_bool')

opt('+menu_map', '',
    option_type='menu_map', add_to_default=False, ctype='!menu_map',
    )


egr()  # }}}


# os {{{
agr('os', 'OS specific tweaks')
opt('wayland_titlebar_color', 'system', option_type='titlebar_color', ctype='uint')
opt('macos_option_as_alt', 'no', option_type='macos_option_as_alt', ctype='uint')
opt('macos_hide_from_tasks', 'no', option_type='to_bool', ctype='bool')
opt('macos_quit_when_last_window_closed', 'no', option_type='to_bool', ctype='bool')
opt('macos_window_resizable', 'yes', option_type='to_bool', ctype='bool')
opt('macos_thicken_font', '0', option_type='positive_float', ctype='float')
opt('macos_traditional_fullscreen', 'no', option_type='to_bool', ctype='bool')
opt('macos_show_window_title_in', 'all', choices=('all', 'menubar', 'none', 'window'), ctype='window_title_in')
opt('macos_menubar_title_max_length', '0', option_type='positive_int', ctype='int')
opt('macos_custom_beam_cursor', 'no', option_type='to_bool')
opt('macos_colorspace', 'srgb', choices=('srgb', 'default', 'displayp3'), ctype='macos_colorspace')
egr()  # }}}


# shortcuts {{{
agr('shortcuts', 'Keyboard shortcuts', '''
Keys are identified simply by their lowercase Unicode characters. For example:
:code:`a` for the :kbd:`A` key, :code:`[` for the left square bracket key, etc.
For functional keys, such as :kbd:`Enter` or :kbd:`Escape`, the names are present
at :ref:`Functional key definitions <functional>`. For modifier keys, the names
are :kbd:`ctrl` (:kbd:`control`, :kbd:`⌃`), :kbd:`shift` (:kbd:`⇧`), :kbd:`alt`
(:kbd:`opt`, :kbd:`option`, :kbd:`⌥`), :kbd:`super` (:kbd:`cmd`, :kbd:`command`,
:kbd:`⌘`).

Simple shortcut mapping is done with the :code:`map` directive. For full details
on advanced mapping including modal and per application maps, see :doc:`mapping`.
Some quick examples to illustrate common tasks::

    # unmap a keyboard shortcut, passing it to the program running in alatty
    map alatty_mod+space
    # completely ignore a keyboard event
    map ctrl+alt+f1 discard_event
    # combine multiple actions
    map alatty_mod+e combine : new_window : next_layout
    # multi-key shortcuts
    map ctrl+x>ctrl+y>z action

The full list of actions that can be mapped to key presses is available
:doc:`here </actions>`.
''')

opt('alatty_mod', 'ctrl+shift',
    option_type='to_modifiers',
    )

opt('clear_all_shortcuts', 'no',
    option_type='clear_all_shortcuts',
    )

opt('+action_alias', 'launch_tab launch --type=tab --cwd=current',
    option_type='action_alias',
    add_to_default=False,
    )

opt('+kitten_alias', 'hints hints --hints-offset=0',
    option_type='kitten_alias',
    add_to_default=False,
    )


# shortcuts.clipboard {{{
agr('shortcuts.clipboard', 'Clipboard')

map('Copy to clipboard',
    'copy_to_clipboard alatty_mod+c copy_to_clipboard',
    )
map('Copy to clipboard',
    'copy_to_clipboard cmd+c copy_to_clipboard',
    only='macos',
    )

map('Paste from clipboard',
    'paste_from_clipboard alatty_mod+v paste_from_clipboard',
    )
map('Paste from clipboard',
    'paste_from_clipboard cmd+v paste_from_clipboard',
    only='macos',
    )

map('Paste from selection',
    'paste_from_selection alatty_mod+s paste_from_selection',
    )
map('Paste from selection',
    'paste_from_selection shift+insert paste_from_selection',
    )

map('Pass selection to program',
    'pass_selection_to_program alatty_mod+o pass_selection_to_program',
    )
egr()  # }}}


# shortcuts.scrolling {{{
agr('shortcuts.scrolling', 'Scrolling')

map('Scroll line up',
    'scroll_line_up alatty_mod+up scroll_line_up',
    )
map('Scroll line up',
    'scroll_line_up alatty_mod+k scroll_line_up',
    )
map('Scroll line up',
    'scroll_line_up opt+cmd+page_up scroll_line_up',
    only='macos',
    )
map('Scroll line up',
    'scroll_line_up cmd+up scroll_line_up',
    only='macos',
    )

map('Scroll line down',
    'scroll_line_down alatty_mod+down scroll_line_down',
    )
map('Scroll line down',
    'scroll_line_down alatty_mod+j scroll_line_down',
    )
map('Scroll line down',
    'scroll_line_down opt+cmd+page_down scroll_line_down',
    only='macos',
    )
map('Scroll line down',
    'scroll_line_down cmd+down scroll_line_down',
    only='macos',
    )

map('Scroll page up',
    'scroll_page_up alatty_mod+page_up scroll_page_up',
    )
map('Scroll page up',
    'scroll_page_up cmd+page_up scroll_page_up',
    only='macos',
    )

map('Scroll page down',
    'scroll_page_down alatty_mod+page_down scroll_page_down',
    )
map('Scroll page down',
    'scroll_page_down cmd+page_down scroll_page_down',
    only='macos',
    )

map('Scroll to top',
    'scroll_home alatty_mod+home scroll_home',
    )
map('Scroll to top',
    'scroll_home cmd+home scroll_home',
    only='macos',
    )

map('Scroll to bottom',
    'scroll_end alatty_mod+end scroll_end',
    )
map('Scroll to bottom',
    'scroll_end cmd+end scroll_end',
    only='macos',
    )

map('Scroll to previous shell prompt',
    'scroll_to_previous_prompt alatty_mod+z scroll_to_prompt -1',
    )

map('Scroll to next shell prompt', 'scroll_to_next_prompt alatty_mod+x scroll_to_prompt 1')

map('Browse scrollback buffer in pager',
    'show_scrollback alatty_mod+h show_scrollback',
    )

map('Browse output of the last shell command in pager',
    'show_last_command_output alatty_mod+g show_last_command_output',
    )
egr()  # }}}


# shortcuts.window {{{
agr('shortcuts.window', 'Window management')

map('New window', 'new_window alatty_mod+enter new_window')
map('New window', 'new_window cmd+enter new_window', only='macos')

map('New OS window', 'new_os_window alatty_mod+n new_os_window')
map('New OS window', 'new_os_window cmd+n new_os_window', only='macos')

map('Close window', 'close_window alatty_mod+w close_window')
map('Close window', 'close_window shift+cmd+d close_window', only='macos')

map('Next window', 'next_window alatty_mod+] next_window')
map('Previous window', 'previous_window alatty_mod+[ previous_window')
map('Move window forward', 'move_window_forward alatty_mod+f move_window_forward')
map('Move window backward', 'move_window_backward alatty_mod+b move_window_backward')
map('Move window to top', 'move_window_to_top alatty_mod+` move_window_to_top')

map('Start resizing window', 'start_resizing_window alatty_mod+r start_resizing_window')
map('Start resizing window', 'start_resizing_window cmd+r start_resizing_window', only='macos')

map('First window', 'first_window alatty_mod+1 first_window')
map('First window', 'first_window cmd+1 first_window', only='macos')

map('Second window', 'second_window alatty_mod+2 second_window')
map('Second window', 'second_window cmd+2 second_window', only='macos')

map('Third window', 'third_window alatty_mod+3 third_window')
map('Third window', 'third_window cmd+3 third_window', only='macos')

map('Fourth window', 'fourth_window alatty_mod+4 fourth_window')
map('Fourth window', 'fourth_window cmd+4 fourth_window', only='macos')

map('Fifth window', 'fifth_window alatty_mod+5 fifth_window')
map('Fifth window', 'fifth_window cmd+5 fifth_window', only='macos')

map('Sixth window', 'sixth_window alatty_mod+6 sixth_window')
map('Sixth window', 'sixth_window cmd+6 sixth_window', only='macos')

map('Seventh window', 'seventh_window alatty_mod+7 seventh_window')
map('Seventh window', 'seventh_window cmd+7 seventh_window', only='macos')

map('Eighth window', 'eighth_window alatty_mod+8 eighth_window')
map('Eighth window', 'eighth_window cmd+8 eighth_window', only='macos')

map('Ninth window', 'ninth_window alatty_mod+9 ninth_window')
map('Ninth window', 'ninth_window cmd+9 ninth_window', only='macos')

map('Tenth window', 'tenth_window alatty_mod+0 tenth_window')
map('Visually select and focus window', 'focus_visible_window alatty_mod+f7 focus_visible_window')
map('Visually swap window with another', 'swap_with_window alatty_mod+f8 swap_with_window')
egr()  # }}}


# shortcuts.tab {{{
agr('shortcuts.tab', 'Tab management')

map('Next tab',
    'next_tab alatty_mod+right next_tab',
    )
map('Next tab',
    'next_tab shift+cmd+] next_tab',
    only='macos',
    )
map('Next tab',
    'next_tab ctrl+tab next_tab',
    )

map('Previous tab',
    'previous_tab alatty_mod+left previous_tab',
    )
map('Previous tab',
    'previous_tab shift+cmd+[ previous_tab',
    only='macos',
    )
map('Previous tab',
    'previous_tab ctrl+shift+tab previous_tab',
    )

map('New tab',
    'new_tab alatty_mod+t new_tab',
    )
map('New tab',
    'new_tab cmd+t new_tab',
    only='macos',
    )

map('Close tab',
    'close_tab alatty_mod+q close_tab',
    )
map('Close tab',
    'close_tab cmd+w close_tab',
    only='macos',
    )

map('Close OS window',
    'close_os_window shift+cmd+w close_os_window',
    only='macos',
    )

map('Move tab forward',
    'move_tab_forward alatty_mod+. move_tab_forward',
    )

map('Move tab backward',
    'move_tab_backward alatty_mod+, move_tab_backward',
    )

map('Set tab title',
    'set_tab_title alatty_mod+alt+t set_tab_title',
    )
map('Set tab title',
    'set_tab_title shift+cmd+i set_tab_title',
    only='macos',
    )
egr('''
You can also create shortcuts to go to specific :term:`tabs <tab>`, with
:code:`1` being the first tab, :code:`2` the second tab and :code:`-1` being the
previously active tab, and any number larger than the last tab being the last
tab::

    map ctrl+alt+1 goto_tab 1
    map ctrl+alt+2 goto_tab 2

Just as with :ac:`new_window` above, you can also pass the name of arbitrary
commands to run when using :ac:`new_tab` and :ac:`new_tab_with_cwd`. Finally,
if you want the new tab to open next to the current tab rather than at the
end of the tabs list, use::

    map ctrl+t new_tab !neighbor [optional cmd to run]
''')  # }}}


# shortcuts.layout {{{
agr('shortcuts.layout', 'Layout management')

map('Next layout',
    'next_layout alatty_mod+l next_layout',
    )
egr('''
You can also create shortcuts to switch to specific :term:`layouts <layout>`::

    map ctrl+alt+t goto_layout tall
    map ctrl+alt+s goto_layout stack

Similarly, to switch back to the previous layout::

    map ctrl+alt+p last_used_layout

There is also a :ac:`toggle_layout` action that switches to the named layout or
back to the previous layout if in the named layout. Useful to temporarily "zoom"
the active window by switching to the stack layout::

    map ctrl+alt+z toggle_layout stack
''')  # }}}


# shortcuts.fonts {{{
agr('shortcuts.fonts', 'Font sizes', '''
You can change the font size for all top-level alatty OS windows at a time or
only the current one.
''')

map('Increase font size',
    'increase_font_size alatty_mod+equal change_font_size all +2.0',
    )
map('Increase font size',
    'increase_font_size alatty_mod+plus change_font_size all +2.0',
    )
map('Increase font size',
    'increase_font_size alatty_mod+kp_add change_font_size all +2.0',
    )
map('Increase font size',
    'increase_font_size cmd+plus change_font_size all +2.0',
    only='macos',
    )
map('Increase font size',
    'increase_font_size cmd+equal change_font_size all +2.0',
    only='macos',
    )
map('Increase font size',
    'increase_font_size shift+cmd+equal change_font_size all +2.0',
    only='macos',
    )

map('Decrease font size',
    'decrease_font_size alatty_mod+minus change_font_size all -2.0',
    )
map('Decrease font size',
    'decrease_font_size alatty_mod+kp_subtract change_font_size all -2.0',
    )
map('Decrease font size',
    'decrease_font_size cmd+minus change_font_size all -2.0',
    only='macos',
    )
map('Decrease font size',
    'decrease_font_size shift+cmd+minus change_font_size all -2.0',
    only='macos',
    )

map('Reset font size',
    'reset_font_size alatty_mod+backspace change_font_size all 0',
    )
map('Reset font size',
    'reset_font_size cmd+0 change_font_size all 0',
    only='macos',
    )
egr('''
To setup shortcuts for specific font sizes::

    map alatty_mod+f6 change_font_size all 10.0

To setup shortcuts to change only the current OS window's font size::

    map alatty_mod+f6 change_font_size current 10.0
''')  # }}}


# shortcuts.selection {{{
agr('shortcuts.selection', 'Select and act on visible text', '''
Use the hints kitten to select text and either pass it to an external program or
insert it into the terminal or copy it to the clipboard.
''')

map('Open URL',
    'open_url alatty_mod+e open_url_with_hints',
    )

map('Insert selected path',
    'insert_selected_path alatty_mod+p>f kitten hints --type path --program -',
    )

map('Open selected path',
    'open_selected_path alatty_mod+p>shift+f kitten hints --type path',
    )

map('Insert selected line',
    'insert_selected_line alatty_mod+p>l kitten hints --type line --program -',
    )

map('Insert selected word',
    'insert_selected_word alatty_mod+p>w kitten hints --type word --program -',
    )

map('Insert selected hash',
    'insert_selected_hash alatty_mod+p>h kitten hints --type hash --program -',
    )

map('Open the selected file at the selected line',
    'goto_file_line alatty_mod+p>n kitten hints --type linenum',
    )

map('Open the selected hyperlink',
    'open_selected_hyperlink alatty_mod+p>y kitten hints --type hyperlink',
    )
egr('''
The hints kitten has many more modes of operation that you can map to different
shortcuts. For a full description see :doc:`hints kitten </kittens/hints>`.
''')  # }}}


# shortcuts.misc {{{
agr('shortcuts.misc', 'Miscellaneous')

map('Toggle fullscreen',
    'toggle_fullscreen alatty_mod+f11 toggle_fullscreen',
    )
map('Toggle fullscreen',
    'toggle_fullscreen ctrl+cmd+f toggle_fullscreen',
    only='macos',
    )

map('Toggle maximized',
    'toggle_maximized alatty_mod+f10 toggle_maximized',
    )

map('Toggle macOS secure keyboard entry',
    'toggle_macos_secure_keyboard_entry opt+cmd+s toggle_macos_secure_keyboard_entry',
    only='macos',
    )

map('Edit config file',
    'edit_config_file alatty_mod+f2 edit_config_file',
    )
map('Edit config file',
    'edit_config_file cmd+, edit_config_file',
    only='macos',
    )

map('Open the alatty command shell',
    'alatty_shell alatty_mod+escape alatty_shell window',
    )

map('Increase background opacity',
    'increase_background_opacity alatty_mod+a>m set_background_opacity +0.1',
    )

map('Decrease background opacity',
    'decrease_background_opacity alatty_mod+a>l set_background_opacity -0.1',
    )

map('Make background fully opaque',
    'full_background_opacity alatty_mod+a>1 set_background_opacity 1',
    )

map('Reset background opacity',
    'reset_background_opacity alatty_mod+a>d set_background_opacity default',
    )

map('Reset the terminal', 'reset_terminal alatty_mod+delete clear_terminal reset active')

map('Reset the terminal',
    'reset_terminal opt+cmd+r clear_terminal reset active',
    only='macos',
    )

map('Clear up to cursor line',
    'clear_terminal_and_scrollback cmd+k clear_terminal to_cursor active',
    only='macos',
    )

map('Reload alatty.conf',
    'reload_config_file alatty_mod+f5 load_config_file',
    )

map('Reload alatty.conf',
    'reload_config_file ctrl+cmd+, load_config_file',
    only='macos'
    )

map('Send arbitrary text on key presses',
    'send_text ctrl+shift+alt+h send_text all Hello World',
    add_to_default=False,
    )

map('Open alatty Website',
    f'open_alatty_website shift+cmd+/ open_url {website_url()}',
    only='macos',
    )

map('Hide macOS alatty application',
    'hide_macos_app cmd+h hide_macos_app',
    only='macos',
    )

map('Hide macOS other applications',
    'hide_macos_other_apps opt+cmd+h hide_macos_other_apps',
    only='macos',
    )

map('Minimize macOS window',
    'minimize_macos_window cmd+m minimize_macos_window',
    only='macos',
    )

map('Quit alatty',
    'quit cmd+q quit',
    only='macos',
    )
egr()  # }}}
egr()  # }}}
